InstituteforDiseaseModeling/idmtools

- idmtools_core/idmtools/services/ipersistance_service.py
Fix #1907 
Fix issue missing from previous initial PR
> Fix cache path (final)

- idmtools_platform_slurm/idmtools_platform_slurm/platform_operations/experiment_operations.py
> Hotfix link (issue #1915)

- idmtools_platform_comps/tests/test_cli.py
- idmtools_platform_slurm/idmtools_platform_slurm/platform_operations/experiment_operations.py
- idmtools_platform_slurm/idmtools_platform_slurm/platform_operations/simulation_operations.py
- idmtools_platform_slurm/idmtools_platform_slurm/platform_operations/suite_operations.py
- idmtools_platform_slurm/idmtools_platform_slurm/plugin_info.py
- idmtools_platform_slurm/idmtools_platform_slurm/slurm_operations/bridged_operations.py
- idmtools_platform_slurm/idmtools_platform_slurm/slurm_operations/local_operations.py
- idmtools_platform_slurm/idmtools_platform_slurm/slurm_operations/operations_interface.py
- idmtools_platform_slurm/idmtools_platform_slurm/slurm_operations/remote_operations.py
- idmtools_slurm_utils/idmtools_slurm_utils/cli.py
- idmtools_slurm_utils/idmtools_slurm_utils/sbatch.py
- idmtools_slurm_utils/idmtools_slurm_utils/scancel.py
- idmtools_slurm_utils/idmtools_slurm_utils/singularity_bridge.py
- idmtools_slurm_utils/idmtools_slurm_utils/utils.py
- idmtools_slurm_utils/idmtools_slurm_utils/verify.py
- idmtools_slurm_utils/idmtools_slurm_utils/watcher.py
Address task #1017
**Note**
- implemented for both LOCAL and BRIDGED cases
- need to be tested with calibra.
> Implement SlurmPlatform cancel feature

- examples/builders/csv_builder_python.py
- idmtools_core/idmtools/builders/csv_simulation_builder.py
- idmtools_core/tests/test_csv_builder.py
- idmtools_core/tests/test_multiple_builders.py
Due to test fail with latest numpy installed
> update numpy type with latest numpy

- dev_scripts/package_requirements.txt
- idmtools_core/build_requirements.txt
Reverts InstituteforDiseaseModeling/idmtools#2024
> Revert "Update coverage requirement from <6.6,>=5.3 to >=5.3,<7.3"

- docs/platforms/slurm/run-script-as-slurm-job.rst
- examples/native_slurm/slurm_job/analyzer_example.py
- examples/native_slurm/slurm_job/example1.py
- examples/native_slurm/slurm_job/example2.py
- examples/native_slurm/slurm_job/sbatch_for_analyzer_example.sh
- examples/native_slurm/slurm_job/sbatch_for_example1.sh
- examples/native_slurm/slurm_job/sbatch_for_example2.sh
- idmtools_platform_slurm/README.md
This PR aims to address the tasks:
#2041 
#2042
> Doc: Run script as Slurm job

- idmtools_platform_comps/idmtools_platform_comps/plugin_info.py
- idmtools_platform_general/MANIFEST.in
- idmtools_platform_slurm/idmtools_platform_slurm/assets/__init__.py
- idmtools_platform_slurm/idmtools_platform_slurm/assets/_run.sh.jinja2
- idmtools_platform_slurm/idmtools_platform_slurm/platform_operations/experiment_operations.py
- idmtools_platform_slurm/idmtools_platform_slurm/platform_operations/utils.py
- idmtools_platform_slurm/idmtools_platform_slurm/slurm_operations/bridged_operations.py
- idmtools_platform_slurm/idmtools_platform_slurm/slurm_operations/local_operations.py
- idmtools_platform_slurm/idmtools_platform_slurm/slurm_operations/operations_interface.py
- idmtools_platform_slurm/tests/test_singularity.py
- idmtools_slurm_utils/idmtools_slurm_utils/bash.py
- idmtools_slurm_utils/idmtools_slurm_utils/utils.py
This PR aims to address
Ticket: Potential issue with max count of simulations in slurm platform #1998 
- Handled the MaxArraySize in Bridged mode case of SlurmPlatform
- Fully support MaxArraySize in cancel experiment functionality
- Fully support MaxArraySize in idmtools-calibra applications
> Handle Slurm MaxArraySize-BRIDGED Mode

- docs/installation.rst
- docs/platforms/slurm/index.rst
- examples/cookbook/python/python-path/python-path.py
- examples/python_model/inputs/ye_seir_model/Assets/SEIR_model.py
- idmtools_models/tests/test_json_configured_task.py
- idmtools_test/idmtools_test/inputs/python/ye_seir_model/Assets/SEIR_model.py
- idmtools_test/idmtools_test/utils/test_task.py
* Fix python 11 issue with dataclasses:
https://github.com/InstituteforDiseaseModeling/idmtools/issues/2083
* Fix previous wrong removed python3.6 emod tests which only run on comps python3.6 environment.
> Fix python 11

- idmtools_platform_comps/idmtools_platform_comps/utils/package_version.py
- idmtools_platform_comps/tests/test_hooks.py
- idmtools_platform_comps/tests/test_logging.py
- idmtools_platform_comps/tests/test_python_experiment.py
- idmtools_platform_general/tests/test_hooks.py
- idmtools_platform_slurm/tests/test_hooks.py
All tests passed except test_logging.py which is still waiting for fix from Zhaowei's PR:#2149
https://jenkins.apps.idmod.org/job/idmtools-Multibranch-Pipeline/view/change-requests/job/PR-2150/
> Add hook tests to comps, file, slurm platforms

- idmtools_core/idmtools/__init__.py
- idmtools_core/idmtools/analysis/platform_analysis_bootstrap.py
- idmtools_core/idmtools/analysis/platform_anaylsis.py
- idmtools_core/idmtools/core/logging.py
- idmtools_core/idmtools/utils/file_parser.py
- idmtools_platform_comps/idmtools_platform_comps/comps_operations/experiment_operations.py
- idmtools_platform_comps/idmtools_platform_comps/comps_operations/suite_operations.py
- idmtools_platform_comps/idmtools_platform_comps/utils/package_version.py
- idmtools_platform_comps/idmtools_platform_comps/utils/spatial_output.py
- idmtools_platform_comps/tests/test_hooks.py
- idmtools_platform_comps/tests/test_logging.py
- idmtools_platform_comps/tests/test_python_experiment.py
- idmtools_platform_general/idmtools_platform_file/platform_operations/asset_collection_operations.py
- idmtools_platform_general/tests/test_hooks.py
- idmtools_platform_slurm/idmtools_platform_slurm/platform_operations/asset_collection_operations.py
- idmtools_platform_slurm/tests/test_hooks.py
Fixed
#1657
#1925
#2138
#2137
#2135
#2136
#2140
> First PR to fix some bugs

- idmtools_core/idmtools/builders/arm_simulation_builder.py
- idmtools_core/idmtools/builders/simulation_builder.py
- idmtools_core/idmtools/builders/sweep_arm.py
- idmtools_platform_container/idmtools_platform_container/container_operations/docker_operations.py
- idmtools_platform_container/idmtools_platform_container/container_platform.py
- idmtools_platform_container/idmtools_platform_container/platform_operations/experiment_operations.py
- idmtools_platform_container/idmtools_platform_container/utils.py
- idmtools_platform_general/idmtools_platform_file/platform_operations/json_metadata_operations.py
This PR includes the initial implementation:
- add docker installation checking
- auto pull image from artifactory
- container name with prefix option
- container_id property
- debug feature
- new implement mounting/binding
- improve checking container
- simplify coding
- add utility
normalize_path
find container folder/file path
> Auto Pull Image, Mounting Checking and Container Name Prefix, etc.

- idmtools_core/idmtools/core/interfaces/irunnable_entity.py
- idmtools_platform_container/idmtools_platform_container/container_operations/docker_operations.py
- idmtools_platform_container/idmtools_platform_container/container_platform.py
- idmtools_platform_container/idmtools_platform_container/platform_operations/experiment_operations.py
- idmtools_platform_container/idmtools_platform_container/utils.py
PR addressed
1. if container_prefix is speficied, start a new container
2. pick first container after sorting by start time
3. now show checking status message for dry_run case
4. fix logger message error
5. display needed information when system is wrong
> Fix some container related issues

- .github/workflows/lint.yml
- .github/workflows/pr-all-test-ubuntu-setup-push.yml
- .github/workflows/pr-all-test-ubuntu-setup.yml
- .github/workflows/run_pip_prod_all_tests.yml
- .github/workflows/run_pip_stage_all_tests.yml
- .github/workflows/staging-idmtools-cli.yml
- .github/workflows/staging-idmtools-core.yml
- .github/workflows/staging-idmtools-models.yml
- .github/workflows/staging-idmtools-platform-comps.yml
- .github/workflows/staging-idmtools-platform-general.yml
- .github/workflows/staging-idmtools-platform-slurm.yml
- .github/workflows/staging-idmtools-slurm-utils.yml
- .github/workflows/staging-idmtools-test.yml
- idmtools_cli/setup.py
- idmtools_core/idmtools/entities/experiment.py
- idmtools_core/idmtools/entities/itask.py
- idmtools_core/idmtools/entities/templated_simulation.py
- idmtools_core/setup.py
- idmtools_models/setup.py
- idmtools_platform_comps/setup.py
- idmtools_platform_container/setup.py
- idmtools_platform_general/setup.py
- idmtools_platform_slurm/setup.py
- idmtools_slurm_utils/setup.py
- idmtools_test/setup.py
> Fix #2298 and remove python3.7 support

- examples/platform_container/container_platform_args_examples.py
- examples/platform_container/extra_packages.py
- examples/platform_container/idmtools.ini
- examples/platform_container/inputs/extra_packages/model_file.py
- examples/platform_container/inputs/python_models/model.py
- examples/platform_container/inputs/python_models/run.sh
- examples/platform_container/python_sims_for_containerplatform.py
- examples/platform_container/python_sims_for_ini.py
- idmtools_platform_container/tests/inputs/model.py
- idmtools_platform_container/tests/test_cli.py
- idmtools_platform_container/tests/test_container_platform.py
- idmtools_platform_container/tests/test_docker_operations.py
- idmtools_platform_container/tests/test_platform_experiment.py
- idmtools_platform_container/tests/utils.py
- idmtools_platform_general/idmtools_platform_file/assets/__init__.py
- idmtools_platform_general/idmtools_platform_file/assets/batch.sh.jinja2
- idmtools_platform_general/idmtools_platform_file/file_platform.py
- Fixed #2278
- Added example for adding extra_package with container platform
- Added unittests for adding extra_package with container platform
- Added more examples for container platform
- Added retries and normalized_path unittests
- Refactor some unittests
> Dynamically install extra packages for container platform

- idmtools_platform_container/idmtools_platform_container/cli/container.py
- idmtools_platform_container/idmtools_platform_container/container_operations/docker_operations.py
- idmtools_platform_container/idmtools_platform_container/container_platform.py
- idmtools_platform_container/idmtools_platform_container/utils/job_history.py
- idmtools_platform_container/idmtools_platform_container/utils/status.py
This PR mainly focus on CLI functionality:
- Cancel Experiment/Simulation by id or job id
- Check Experiment/Simulation status by id or job id
- Check running jobs
- Check job history
- Check container history
- Check job details
- Check individual job details
- Check container history used by user
- ...
> Implement Cancel, Status and Job History functionality on Container platform

- idmtools_platform_container/idmtools_platform_container/container_platform.py
This PR aims to make sure ContainerPlatform works on both Windows and Linux.
> ContainerPlatform works on Linux

- idmtools_platform_container/idmtools_platform_container/cli/container.py
- idmtools_platform_container/idmtools_platform_container/container_operations/docker_operations.py
- idmtools_platform_container/idmtools_platform_container/container_platform.py
- idmtools_platform_container/idmtools_platform_container/platform_operations/experiment_operations.py
- idmtools_platform_container/idmtools_platform_container/platform_operations/simulation_operations.py
- idmtools_platform_container/idmtools_platform_container/utils/general.py
- idmtools_platform_container/idmtools_platform_container/utils/job_history.py
- idmtools_platform_container/idmtools_platform_container/utils/status.py
- idmtools_platform_general/idmtools_platform_file/assets/_run.sh.jinja2
- idmtools_platform_general/idmtools_platform_file/assets/batch.sh.jinja2
This PR aims to
- Support user container
- Implement cancel & delete for Calibra application
- Improve user container validation (validate_container returns short id)
- Validate docker environment as early as possible
- Add length checking for packages to be installed
- Fix CLI history paging
- Improve some CLI display (color and count)
- Restrict idmtools container --help
- Code cleanup: fix docstring, etc.
> Support user container and implement cancel & delete for Calibra applications, etc.

- docs/platforms/comps/scheduling.rst
- examples/python_model/inputs/python_model_with_deps/Assets/model.py
- examples/python_model/inputs/scheduling/WorkOrder.json
- examples/python_model/inputs/scheduling/hpc/WorkOrder.json
- examples/python_model/python_sim_scheduling.py
- examples/python_model/python_sim_scheduling_by_config.py
- examples/python_model/python_sim_scheduling_hpc.py
- idmtools_platform_comps/idmtools_platform_comps/utils/scheduling.py
- idmtools_platform_comps/tests/test_analyzers_python_comps.py
- idmtools_platform_comps/tests/test_workorder.py
- Fixed #2318 
- Added more example
- Updated tests
- Update docs
> Fix dynamic scheduling issue #2318

- idmtools_platform_general/idmtools_platform_file/platform_operations/suite_operations.py
- idmtools_platform_slurm/idmtools_platform_slurm/platform_operations/suite_operations.py
> Fix suite's experiments cache issue

- idmtools_core/idmtools/core/interfaces/irunnable_entity.py
- idmtools_core/idmtools/entities/experiment.py
- idmtools_platform_comps/idmtools_platform_comps/utils/assetize_output/assetize_output.py
- idmtools_platform_comps/tests/test_comps_platform.py
> Fixed #2037: remove wait_on_done complately

- idmtools_platform_general/idmtools_platform_file/file_platform.py
- idmtools_platform_general/idmtools_platform_file/platform_operations/asset_collection_operations.py
- idmtools_platform_general/idmtools_platform_file/platform_operations/experiment_operations.py
- idmtools_platform_general/idmtools_platform_file/platform_operations/utils.py
- idmtools_platform_slurm/idmtools_platform_slurm/slurm_operations/local_operations.py
This PR aims to implement feature request #2143
> Make readable/meaningful suite/experiment/simulation output directory names

- idmtools_cli/setup.py
- idmtools_core/setup.py
- idmtools_core/tests/test_platform_factory.py
- idmtools_models/setup.py
- idmtools_models/tests/test_experiment.py
- idmtools_platform_comps/setup.py
- idmtools_platform_comps/tests/idmtools.ini
- idmtools_platform_comps/tests/test_add_simulations_to_experiment.py
- idmtools_platform_comps/tests/test_platform_factory.py
- idmtools_platform_comps/tests/test_retrieval.py
- idmtools_platform_container/setup.py
- idmtools_platform_container/tests/test_platform_experiment.py
- idmtools_platform_general/setup.py
- idmtools_platform_general/tests/test_folder.py
- idmtools_platform_slurm/setup.py
- idmtools_platform_slurm/tests/helper.py
- idmtools_platform_slurm/tests/test_folder.py
- idmtools_platform_slurm/tests/test_suite_experiment.py
- idmtools_slurm_utils/setup.py
- idmtools_test/setup.py
Also fixed #2312 for uploading package to pypi server
> add testcases for #2313, #2171 and #2028

- idmtools_core/idmtools/config/idm_config_parser.py
- idmtools_core/idmtools/core/platform_factory.py
- idmtools_core/tests/test_platform_factory.py
- idmtools_platform_container/tests/test_max_file_path.py
Display INI file found info only when INI exists
Log Platform inputs info to log file
> Log info to file in CLI case

- idmtools_platform_general/idmtools_platform_file/platform_operations/json_metadata_operations.py
- idmtools_platform_slurm/idmtools_platform_slurm/platform_operations/json_metadata_operations.py
Aim to address #2388 and #2389
> Improve get_item by adding suffix to search

- idmtools_platform_general/idmtools_platform_file/file_platform.py
> Fix parent issue in get_directory for File/Container/Process Platform

- idmtools_platform_comps/idmtools_platform_comps/comps_operations/suite_operations.py
- idmtools_platform_general/idmtools_platform_file/platform_operations/suite_operations.py
- idmtools_platform_slurm/idmtools_platform_slurm/platform_operations/suite_operations.py
> Check suite existence before delete

- idmtools_platform_container/idmtools_platform_container/container_operations/docker_operations.py
- idmtools_platform_container/tests/test_container_platform.py
- idmtools_platform_container/tests/test_platform_experiment.py
- idmtools_platform_general/tests/test_platform_file.py
- idmtools_platform_general/tests/test_platform_process.py
> Fix docker container become unusable case in linux

- idmtools_core/idmtools/entities/command_line.py
This PR aims to address the #2413
> Fix CommandLine option quote issue

- idmtools_core/idmtools/builders/arm_simulation_builder.py
- idmtools_core/idmtools/entities/templated_simulation.py
- idmtools_platform_comps/tests/test_simulation_builder.py
> Fix #2426: support re-use SweepArm

- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
- .vscode/launch.json
- .vscode/settings.json
> Add Devcontainer for codespaces

- dev_scripts/bootstrap.py
- idmtools_core/idmtools/analysis/analyze_manager.py
This PR addresses the tickets:
#2482
#2478 
#2207
> Update Dev script to fix some issues

- idmtools_cli/LICENSE.TXT
- idmtools_cli/MANIFEST.in
- idmtools_core/LICENSE.TXT
- idmtools_core/MANIFEST.in
- idmtools_models/LICENSE.TXT
- idmtools_models/MANIFEST.in
- idmtools_platform_comps/LICENSE.TXT
- idmtools_platform_comps/MANIFEST.in
- idmtools_platform_container/LICENSE.TXT
- idmtools_platform_container/MANIFEST.in
- idmtools_platform_general/LICENSE.TXT
- idmtools_platform_general/MANIFEST.in
- idmtools_platform_slurm/LICENSE.TXT
- idmtools_platform_slurm/MANIFEST.in
- idmtools_test/LICENSE.TXT
- idmtools_test/MANIFEST.in
To fix build complains for ssmt and other docker build issue
Need to copy LICENSE.TXT under each package
> Add LICENSE.TXT and add include LICENSE.TXT in MANIFEST.in 

- idmtools_core/idmtools/entities/experiment.py
- idmtools_core/idmtools/entities/simulation.py
- idmtools_core/idmtools/entities/suite.py
- idmtools_core/idmtools/entities/templated_simulation.py
- idmtools_core/idmtools/utils/collections.py
- idmtools_platform_general/idmtools_platform_file/platform_operations/experiment_operations.py
- idmtools_platform_general/idmtools_platform_file/platform_operations/simulation_operations.py
- idmtools_platform_general/idmtools_platform_file/platform_operations/utils.py
- Fixed: #2553
- Fixed: #2554
- Fixed: #2555 
- Fixed: #2556 
- Fixed: #2557 
- Fixed: #2558 
- Fixed: #2559 
- Fixed: #2561
Created this PR for @ZDu-IDM due to his Github login issue
> Cleanup entity parent
